### PR TITLE
Remove Minizip from UnzipKit headers

### PR DESCRIPTION
**Pull request by iblacksun**
Remove Minizip from UnzipKit Header.

So now UnzipKit can using in Swift Frameworks.

### CODE REVIEW

**Comment by abbeycode** [comment]
Hey, so is this what DTS recommended as the solution to #21? Also, please note that this pull request broke the build. Looking at the Travis logs, it seems that the unit tests are failing to build.

**Comment by abbeycode** [comment]
Will you be able to take a look at the unit test build failure? Let me know if you can't, and I can take a look.

**Comment by iblacksun** [comment]
@abbeycode  I have no experience with Travis CI. Could you take a look at it?

**Comment by abbeycode** [comment]
There's really not anything to learn with Travis, it's just running a command line build. You almost certainly don't need to change the way the build is actually configured. Before I look, can you try running the unit tests locally and see if it works? If it doesn't (the logs indicate the unit tests aren't successfully building on your branch), then fix it and push. You should see the warning below that "All checks have failed" go away.

If you still would rather I take a look, I'll see what's going on with it.

**Comment by iblacksun** [comment]
@abbeycode OK, Thanks you very much. I will try to fix this and request your help if have any question.

**Comment by iblacksun** [comment]
@abbeycode Now Travis CI all checks have passed. Please check it again.

**Comment by abbeycode** [comment]
Hey, thanks for tackling it. I've made a few changes on the [swift-framework](https://github.com/abbeycode/UnzipKit/tree/swift-framework) branch. It looks like your UnzipKitIssue project builds fine with it. Can you please take a look? If it looks good, I'll merge to `master` and cut a new release.

If you're interested in the reasons for the specific changes I made, let me know, and I can annotate your PR with inline comments.

**Comment by iblacksun** [comment]
@abbeycode I've check ```UnzipKitIssue``` project and can build fine now.

Thanks.

**Comment by abbeycode** [comment]
This has been incorporated into v1.6. Thanks for the help!

**Pull request merged**
